# Generated by Django 4.2.4 on 2023-12-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_emails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
