# Generated by Django 4.2.4 on 2023-12-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_value',
            field=models.IntegerField(),
        ),
    ]
