# Generated by Django 4.2.4 on 2023-12-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_alter_skills_skill_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_url',
            field=models.URLField(default='https://github.com/jonie20', max_length=2000),
        ),
    ]
