# Generated by Django 4.2.4 on 2023-12-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_projects_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_url', models.URLField(default='https://github.com/jonie20', max_length=2000)),
                ('badge_image', models.ImageField(blank=True, default='default_project.jpg', null=True, upload_to='Badges/images')),
            ],
        ),
    ]
